/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessageView {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface CommentView {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface DailyTask {
  'day' : string,
  'completed' : boolean,
  'target' : string,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface PostView {
  'id' : bigint,
  'likedBy' : Array<Principal>,
  'author' : Principal,
  'likes' : bigint,
  'timestamp' : Time,
  'caption' : string,
  'image' : ExternalBlob,
  'comments' : Array<CommentView>,
}
export type TestCategory = { 'previousYearPaperYear' : bigint } |
  { 'mockTest' : null };
export interface TestResult {
  'subCategory' : [] | [string],
  'exam' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'incorrectCount' : bigint,
  'timestamp' : Time,
  'category' : TestCategory,
  'correctCount' : bigint,
  'accuracy' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'clearDashboardBackground' : ActorMethod<[], undefined>,
  'createPost' : ActorMethod<[ExternalBlob, string], bigint>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllPosts' : ActorMethod<[], Array<PostView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessageView>>,
  'getComments' : ActorMethod<[bigint], Array<CommentView>>,
  'getDailyTarget' : ActorMethod<[], [] | [DailyTask]>,
  'getDailyTaskStatus' : ActorMethod<[string], string>,
  'getDashboardBackground' : ActorMethod<[], [] | [ExternalBlob]>,
  'getTestHistory' : ActorMethod<[], Array<TestResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markDailyTargetCompleted' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDashboardBackground' : ActorMethod<[ExternalBlob], undefined>,
  'saveTestResult' : ActorMethod<[TestResult], undefined>,
  'sendMessage' : ActorMethod<[string], bigint>,
  'setDailyTarget' : ActorMethod<[string, string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];